### PR TITLE
Changed CODAP standalone parameter value from true to SageModeler

### PR DESCRIPTION
**Pull request by dougmartin**
This enabled drag/drop of gameviews while ensuring that Sage stays as a full screen DI in the background.

### CODE REVIEW

**Comment by dougmartin** [comment]
@dstrawberrygirl please review but I may hold off merging this.

**Comment by dougmartin** [comment]
@dstrawberrygirl the `standalone` url param was an existing boolean parameter that Jonathan then extended to be boolean + string.  If it is a string value then the data interactive that identifies itself with that string becomes the standalone (background) interactive and CODAP then allows other interactives to be loaded above it in its windowing system.  If the boolean value is used then only one interactive is allowed and it is always in the background.  By using the string value we are now allowing other data interactives (like the sensor interactive) to be active alongside sage.

The reason for the mixed case is a little crazy.  CODAP is supposed to use the `name` registered when the interactive connects to CODAP but instead it is using the title, which in this case is `SageModeler`.  Jonathan is looking into why the name is not being used.

**Comment by dougmartin** [comment]
@dstrawberrygirl forgot to mention these url parameters are used in the iframe that sagemodeler creates to load CODAP - users won't be setting/using them.

**Comment by dstrawberrygirl** [comment]
@dougmartin thanks for the info! Looks good to me. 👍

**Pull request merged**
